version: '3.7'

services:
  redis-store:
    container_name: redis.accounts.larcity
    image: redis:7
    restart: unless-stopped
    ports:
      - '16079:6379'
    volumes:
      - ./db/development/redis:/data

  app-store:
    container_name: db.accounts.larcity
    image: postgres:13.13
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${APP_DATABASE_NAME}
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust # IMPORTANT allows all connections without a password - experimental only!
    ports:
      - '16032:5432'
    volumes:
      - ./db/development/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/development/postgres/data:/var/lib/postgresql/data
      - ./db/development/postgres/downloads:/usr/local/downloads

  doc-store:
    container_name: mongodb.accounts.larcity
    # Mongodb versions: https://github.com/docker-library/docs/blob/master/mongo/README.md#supported-tags-and-respective-dockerfile-links
    image: mongo:7.0-jammy
    restart: unless-stopped
    volumes:
      # Read more: https://registry.hub.docker.com/_/mongo
      - ./db/development/mongodb/data:/data/db
      - ./db/development/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "16017:27017"
    # env_file:
    #   - ./.mongodb/.env.development
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

  doc-store-admin:
    container_name: mongodb-admin.accounts.larcity
    image: mongo-express
    restart: unless-stopped
    ports:
      - "16081:8081"
    # env_file:
    #   - ./.mongodb/.env.development
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb.accounts.larcity
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: Test1234
    depends_on:
      - doc-store

networks:
  default:
    driver: bridge
